-- public.memoria_thread definição

-- Drop table

-- DROP TABLE public.memoria_thread;

CREATE TABLE public.memoria_thread (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	memoria text DEFAULT ''::text NOT NULL,
	thread_id uuid NULL,
	tipo_memoria text NULL,
	CONSTRAINT memoria_usuario_pkey PRIMARY KEY (id)
);


-- public.memoria_usuario definição

-- Drop table

-- DROP TABLE public.memoria_usuario;

CREATE TABLE public.memoria_usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	memoria text DEFAULT ''::text NOT NULL,
	account_id uuid NULL,
	tipo_memoria text NULL,
	aprovacao_usuario bool DEFAULT false NULL,
	aprovado_em timestamptz NULL,
	CONSTRAINT memoria_usuario_pkey1 PRIMARY KEY (id)
);

-- public.memoria_usuario chaves estrangeiras

ALTER TABLE public.memoria_usuario ADD CONSTRAINT memoria_usuario_account_id_fkey FOREIGN KEY (account_id) REFERENCES auth.users(id);

-- public.memoria_thread chaves estrangeiras    

ALTER TABLE public.memoria_thread ADD CONSTRAINT memoria_usuario_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.threads(thread_id);


GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.memoria_thread TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.memoria_usuario TO service_role;

alter table
    public.memoria_thread
    enable row level security;

alter table
    public.memoria_usuario
    enable row level security;