create table public.usuario_celular (
  id bigint generated by default as identity not null,
  celular text not null,
  created_at timestamp with time zone not null default now(),
  account_id uuid not null,
  constraint usuario_celular_pkey primary key (id),
  constraint usuario_celular_account_id_key unique (account_id),
  constraint usuario_celular_celular_key unique (celular),
  constraint usuario_celular_account_id_fkey foreign KEY (account_id) references auth.users (id) on delete cascade
) TABLESPACE pg_default;

-- Function to get user's phone number (to be used by authenticated functions)
create or replace function public.get_user_phone_number(user_id uuid)
returns table (celular text) as $$
begin
  return query 
  select uc.celular 
  from public.usuario_celular uc 
  where uc.account_id = user_id;
end;
$$ language plpgsql security definer;


-- Enable RLS on the table
ALTER TABLE public.usuario_celular ENABLE ROW LEVEL SECURITY;

-- Allow the function to bypass RLS
ALTER FUNCTION public.get_user_phone_number(user_id uuid) OWNER TO postgres;

-- Policy to allow users to view their own phone number
CREATE POLICY "Users can view their own phone number"
ON public.usuario_celular
FOR SELECT
USING (auth.uid() = account_id);

-- Policy to allow users to insert their own phone number
CREATE POLICY "Users can insert their own phone number"
ON public.usuario_celular
FOR INSERT
WITH CHECK (auth.uid() = account_id);

-- Policy to allow users to update their own phone number
CREATE POLICY "Users can update their own phone number"
ON public.usuario_celular
FOR UPDATE
USING (auth.uid() = account_id);

-- Policy to allow users to delete their own phone number
CREATE POLICY "Users can delete their own phone number"
ON public.usuario_celular
FOR DELETE
USING (auth.uid() = account_id);
